name: docker-build-publish
on: [push]

jobs:
  publish-rallly-arm64:
    runs-on: ubuntu-latest
    env:
      RALLLY_VERSION: 'v3.11.2'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache
        
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/${{ github.repository_owner }}/rallly:${{ env.RALLLY_VERSION }}
          build-args: |
            APP_VERSION=${{ env.RALLLY_VERSION }}
            SELF_HOSTED=true
